Repository 9oormthon-univ/2025_SEASONTHON_TEAM_45_BE, pull requests merged in 2025-08, with the labels that each got.

#2 기본 프로젝트 공통 설정 및 전역 응답 템플릿 추가
  build.gradle
  src/main/java/org/carefreepass/com/carefreepassserver/CareFreePassServerApplication.java
  src/main/java/org/carefreepass/com/carefreepassserver/golbal/config/JpaAuditingConfig.java
  src/main/java/org/carefreepass/com/carefreepassserver/golbal/config/RedisConfig.java
  src/main/java/org/carefreepass/com/carefreepassserver/golbal/config/SecurityConfig.java
  src/main/java/org/carefreepass/com/carefreepassserver/golbal/config/SwaggerConfig.java
  src/main/java/org/carefreepass/com/carefreepassserver/golbal/domain/BaseTimeEntity.java
  src/main/java/org/carefreepass/com/carefreepassserver/golbal/domain/Status.java
  src/main/java/org/carefreepass/com/carefreepassserver/golbal/error/BusinessException.java
  src/main/java/org/carefreepass/com/carefreepassserver/golbal/error/ErrorCode.java
  src/main/java/org/carefreepass/com/carefreepassserver/golbal/error/ErrorResponse.java
  src/main/java/org/carefreepass/com/carefreepassserver/golbal/error/GlobalExceptionHandler.java
  src/main/java/org/carefreepass/com/carefreepassserver/golbal/log/BusinessExceptionLogEntry.java
  src/main/java/org/carefreepass/com/carefreepassserver/golbal/log/ExceptionLogEntry.java
  src/main/java/org/carefreepass/com/carefreepassserver/golbal/properties/RedisProperties.java
  src/main/java/org/carefreepass/com/carefreepassserver/golbal/properties/SwaggerProperties.java
  src/main/java/org/carefreepass/com/carefreepassserver/golbal/response/ApiResponseTemplate.java
  src/main/resources/application-datasource.yml
  src/main/resources/application-dev.yml
  src/main/resources/application-local.yml
  src/main/resources/application-redis.yml
  src/main/resources/application.properties
  src/main/resources/application.yml
Labels: Setting

#4 환자 자체 로그인 기능 구현
  build.gradle
  src/main/java/org/carefreepass/com/carefreepassserver/domain/auth/controller/AuthController.java
  src/main/java/org/carefreepass/com/carefreepassserver/domain/auth/controller/docs/AuthDocs.java
  src/main/java/org/carefreepass/com/carefreepassserver/domain/auth/dto/AccessTokenDto.java
  src/main/java/org/carefreepass/com/carefreepassserver/domain/auth/dto/RefreshTokenDto.java
  src/main/java/org/carefreepass/com/carefreepassserver/domain/auth/dto/request/PatientSignInRequest.java
  src/main/java/org/carefreepass/com/carefreepassserver/domain/auth/dto/request/PatientSignUpRequest.java
  src/main/java/org/carefreepass/com/carefreepassserver/domain/auth/dto/request/RefreshTokenRequest.java
  src/main/java/org/carefreepass/com/carefreepassserver/domain/auth/dto/response/TokenPairResponse.java
  src/main/java/org/carefreepass/com/carefreepassserver/domain/auth/entity/domain/RefreshToken.java
  src/main/java/org/carefreepass/com/carefreepassserver/domain/auth/entity/domain/TokenType.java
  src/main/java/org/carefreepass/com/carefreepassserver/domain/auth/repository/RefreshTokenRepository.java
  src/main/java/org/carefreepass/com/carefreepassserver/domain/auth/service/AuthService.java
  src/main/java/org/carefreepass/com/carefreepassserver/domain/auth/service/PatientAuthService.java
  src/main/java/org/carefreepass/com/carefreepassserver/domain/member/entity/Gender.java
  src/main/java/org/carefreepass/com/carefreepassserver/domain/member/entity/Member.java
  src/main/java/org/carefreepass/com/carefreepassserver/domain/member/entity/MemberRole.java
  src/main/java/org/carefreepass/com/carefreepassserver/domain/member/entity/MemberType.java
  src/main/java/org/carefreepass/com/carefreepassserver/domain/member/entity/PatientProfile.java
  src/main/java/org/carefreepass/com/carefreepassserver/domain/member/repository/MemberRepository.java
  src/main/java/org/carefreepass/com/carefreepassserver/domain/member/repository/PatientProfileRepository.java
  src/main/java/org/carefreepass/com/carefreepassserver/golbal/config/SecurityConfig.java
  src/main/java/org/carefreepass/com/carefreepassserver/golbal/constant/SecurityConstant.java
  src/main/java/org/carefreepass/com/carefreepassserver/golbal/error/ErrorCode.java
  src/main/java/org/carefreepass/com/carefreepassserver/golbal/filter/JwtAuthenticationFilter.java
  src/main/java/org/carefreepass/com/carefreepassserver/golbal/properties/JwtProperties.java
  src/main/java/org/carefreepass/com/carefreepassserver/golbal/security/JwtTokenProvider.java
  src/main/java/org/carefreepass/com/carefreepassserver/golbal/security/PrincipalDetails.java
  src/main/java/org/carefreepass/com/carefreepassserver/golbal/util/JwtUtil.java
  src/main/java/org/carefreepass/com/carefreepassserver/golbal/util/MemberUtil.java
  src/main/java/org/carefreepass/com/carefreepassserver/golbal/util/SecurityUtil.java
  src/main/resources/application-security.yml
Labels: Feature

#11 Cicd/#9
  .github/workflows/deploy.yml
  build.gradle
  src/main/resources/application-test.yml
  src/test/java/org/carefreepass/com/carefreepassserver/CareFreePassServerApplicationTests.java
Labels: Devops

#15 refactor/#14
  docs/fcm_implementation_guide.md
  src/main/java/org/carefreepass/com/carefreepassserver/domain/appointment/controller/AppointmentController.java
  src/main/java/org/carefreepass/com/carefreepassserver/domain/appointment/dto/request/AppointmentCheckinRequest.java
  src/main/java/org/carefreepass/com/carefreepassserver/domain/appointment/dto/request/AppointmentCreateRequest.java
  src/main/java/org/carefreepass/com/carefreepassserver/domain/appointment/dto/request/AppointmentUpdateRequest.java
  src/main/java/org/carefreepass/com/carefreepassserver/domain/appointment/dto/response/AppointmentResponse.java
  src/main/java/org/carefreepass/com/carefreepassserver/domain/appointment/entity/Appointment.java
  src/main/java/org/carefreepass/com/carefreepassserver/domain/appointment/repository/AppointmentRepository.java
  src/main/java/org/carefreepass/com/carefreepassserver/domain/appointment/service/AppointmentService.java
  src/main/java/org/carefreepass/com/carefreepassserver/domain/auth/dto/AccessTokenDto.java
  src/main/java/org/carefreepass/com/carefreepassserver/domain/auth/dto/RefreshTokenDto.java
  src/main/java/org/carefreepass/com/carefreepassserver/domain/auth/dto/request/RefreshTokenRequest.java
  src/main/java/org/carefreepass/com/carefreepassserver/domain/auth/repository/RefreshTokenRepository.java
  src/main/java/org/carefreepass/com/carefreepassserver/domain/chat/controller/ChatController.java
  src/main/java/org/carefreepass/com/carefreepassserver/domain/chat/dto/request/ChatMessageRequest.java
  src/main/java/org/carefreepass/com/carefreepassserver/domain/chat/dto/request/ChatStartRequest.java
  src/main/java/org/carefreepass/com/carefreepassserver/domain/chat/dto/response/ChatMessageResponse.java
  src/main/java/org/carefreepass/com/carefreepassserver/domain/chat/dto/response/ChatSessionResponse.java
  src/main/java/org/carefreepass/com/carefreepassserver/domain/chat/dto/response/SymptomAnalysisResponse.java
  src/main/java/org/carefreepass/com/carefreepassserver/domain/chat/entity/ChatMessage.java
  src/main/java/org/carefreepass/com/carefreepassserver/domain/chat/entity/ChatSession.java
  src/main/java/org/carefreepass/com/carefreepassserver/domain/chat/entity/ChatSessionStatus.java
  src/main/java/org/carefreepass/com/carefreepassserver/domain/chat/entity/MessageSenderType.java
  src/main/java/org/carefreepass/com/carefreepassserver/domain/chat/entity/SymptomAnalysis.java
  src/main/java/org/carefreepass/com/carefreepassserver/domain/chat/repository/ChatMessageRepository.java
  src/main/java/org/carefreepass/com/carefreepassserver/domain/chat/repository/ChatSessionRepository.java
  src/main/java/org/carefreepass/com/carefreepassserver/domain/chat/repository/SymptomAnalysisRepository.java
  src/main/java/org/carefreepass/com/carefreepassserver/domain/chat/service/AiChatService.java
  src/main/java/org/carefreepass/com/carefreepassserver/domain/chat/service/AppointmentBookingService.java
  src/main/java/org/carefreepass/com/carefreepassserver/domain/chat/service/OpenAIService.java
  src/main/java/org/carefreepass/com/carefreepassserver/domain/member/repository/MemberRepository.java
  src/main/java/org/carefreepass/com/carefreepassserver/domain/notification/controller/NotificationController.java
  src/main/java/org/carefreepass/com/carefreepassserver/domain/notification/dto/request/DeviceTokenRegisterRequest.java
  src/main/java/org/carefreepass/com/carefreepassserver/domain/notification/dto/request/PatientCallRequest.java
  src/main/java/org/carefreepass/com/carefreepassserver/domain/notification/dto/response/NotificationHistoryResponse.java
  src/main/java/org/carefreepass/com/carefreepassserver/domain/notification/repository/DeviceTokenRepository.java
  src/main/java/org/carefreepass/com/carefreepassserver/domain/notification/repository/NotificationHistoryRepository.java
  src/main/java/org/carefreepass/com/carefreepassserver/domain/notification/service/NotificationService.java
  src/main/java/org/carefreepass/com/carefreepassserver/golbal/config/ChatProperties.java
  src/main/java/org/carefreepass/com/carefreepassserver/golbal/config/OpenAIProperties.java
  src/main/java/org/carefreepass/com/carefreepassserver/golbal/error/ErrorCode.java
  src/main/java/org/carefreepass/com/carefreepassserver/golbal/error/ErrorResponse.java
  src/main/java/org/carefreepass/com/carefreepassserver/golbal/error/GlobalExceptionHandler.java
  src/main/resources/application-datasource.yml
  src/main/resources/application.yml
  src/main/resources/static/chat-test.html
  src/main/resources/static/test-fcm.html
Labels: Refactor
