Repository 9oormthon-univ/2025_SEASONTHON_TEAM_45_BE, pull requests merged in 2025-09, with the labels that each got.

#20 Feature/#19
  docs/chat/websocket-guide.md
  src/main/java/org/carefreepass/com/carefreepassserver/domain/appointment/controller/AppointmentController.java
  src/main/java/org/carefreepass/com/carefreepassserver/domain/appointment/controller/PatientTimeSlotController.java
  src/main/java/org/carefreepass/com/carefreepassserver/domain/appointment/controller/docs/AppointmentDocs.java
  src/main/java/org/carefreepass/com/carefreepassserver/domain/appointment/controller/docs/PatientTimeSlotDocs.java
  src/main/java/org/carefreepass/com/carefreepassserver/domain/appointment/dto/request/AppointmentCreateRequest.java
  src/main/java/org/carefreepass/com/carefreepassserver/domain/appointment/dto/request/AppointmentUpdateRequest.java
  src/main/java/org/carefreepass/com/carefreepassserver/domain/appointment/dto/response/AppointmentResponse.java
  src/main/java/org/carefreepass/com/carefreepassserver/domain/appointment/dto/response/AvailableTimeSlotsResponse.java
  src/main/java/org/carefreepass/com/carefreepassserver/domain/appointment/dto/response/TimeSlotResponse.java
  src/main/java/org/carefreepass/com/carefreepassserver/domain/appointment/entity/Appointment.java
  src/main/java/org/carefreepass/com/carefreepassserver/domain/appointment/entity/AppointmentStatus.java
  src/main/java/org/carefreepass/com/carefreepassserver/domain/appointment/repository/AppointmentRepository.java
  src/main/java/org/carefreepass/com/carefreepassserver/domain/appointment/service/AppointmentService.java
  src/main/java/org/carefreepass/com/carefreepassserver/domain/appointment/service/TimeSlotService.java
  src/main/java/org/carefreepass/com/carefreepassserver/domain/auth/dto/response/TokenPairResponse.java
  src/main/java/org/carefreepass/com/carefreepassserver/domain/auth/service/HospitalAuthService.java
  src/main/java/org/carefreepass/com/carefreepassserver/domain/auth/service/PatientAuthService.java
  src/main/java/org/carefreepass/com/carefreepassserver/domain/chat/controller/ChatController.java
  src/main/java/org/carefreepass/com/carefreepassserver/domain/chat/entity/ChatMessage.java
  src/main/java/org/carefreepass/com/carefreepassserver/domain/chat/entity/SymptomAnalysis.java
  src/main/java/org/carefreepass/com/carefreepassserver/domain/chat/service/AppointmentBookingService.java
  src/main/java/org/carefreepass/com/carefreepassserver/domain/chat/service/OpenAIService.java
  src/main/java/org/carefreepass/com/carefreepassserver/domain/hospital/controller/HospitalDepartmentController.java
  src/main/java/org/carefreepass/com/carefreepassserver/domain/hospital/controller/TimeSlotExceptionController.java
  src/main/java/org/carefreepass/com/carefreepassserver/domain/hospital/controller/docs/HospitalDepartmentDocs.java
  src/main/java/org/carefreepass/com/carefreepassserver/domain/hospital/controller/docs/TimeSlotExceptionDocs.java
  src/main/java/org/carefreepass/com/carefreepassserver/domain/hospital/dto/request/HospitalDepartmentCreateRequest.java
  src/main/java/org/carefreepass/com/carefreepassserver/domain/hospital/dto/request/HospitalDepartmentUpdateRequest.java
  src/main/java/org/carefreepass/com/carefreepassserver/domain/hospital/dto/request/TimeSlotBlockRequest.java
  src/main/java/org/carefreepass/com/carefreepassserver/domain/hospital/dto/response/HospitalDepartmentResponse.java
  src/main/java/org/carefreepass/com/carefreepassserver/domain/hospital/dto/response/TimeSlotExceptionResponse.java
  src/main/java/org/carefreepass/com/carefreepassserver/domain/hospital/entity/HospitalDepartment.java
  src/main/java/org/carefreepass/com/carefreepassserver/domain/hospital/entity/TimeSlotException.java
  src/main/java/org/carefreepass/com/carefreepassserver/domain/hospital/repository/HospitalDepartmentRepository.java
  src/main/java/org/carefreepass/com/carefreepassserver/domain/hospital/repository/TimeSlotExceptionRepository.java
  src/main/java/org/carefreepass/com/carefreepassserver/domain/hospital/service/HospitalDepartmentService.java
  src/main/java/org/carefreepass/com/carefreepassserver/domain/hospital/service/TimeSlotExceptionService.java
  src/main/java/org/carefreepass/com/carefreepassserver/domain/member/entity/Member.java
  src/main/java/org/carefreepass/com/carefreepassserver/domain/notification/controller/NotificationController.java
  src/main/java/org/carefreepass/com/carefreepassserver/domain/notification/controller/docs/NotificationDocs.java
  src/main/java/org/carefreepass/com/carefreepassserver/domain/notification/dto/request/PatientCallRequest.java
  src/main/java/org/carefreepass/com/carefreepassserver/domain/notification/service/FcmService.java
  src/main/java/org/carefreepass/com/carefreepassserver/domain/notification/service/NotificationService.java
  src/main/java/org/carefreepass/com/carefreepassserver/golbal/config/FirebaseConfig.java
  src/main/java/org/carefreepass/com/carefreepassserver/golbal/config/SecurityConfig.java
  src/main/java/org/carefreepass/com/carefreepassserver/golbal/error/ErrorCode.java
  src/main/java/org/carefreepass/com/carefreepassserver/golbal/security/JwtTokenProvider.java
  src/main/resources/application-datasource.yml
  src/main/resources/application-local.yml
  src/main/resources/static/chat-test.html
  src/main/resources/static/signup.html
  src/main/resources/static/test-complete.html
Labels: Feature, Refactor, Docs

#26 문자 인증 기능 구현
  build.gradle
  src/main/java/org/carefreepass/com/carefreepassserver/domain/auth/controller/AuthController.java
  src/main/java/org/carefreepass/com/carefreepassserver/domain/auth/controller/docs/AuthDocs.java
  src/main/java/org/carefreepass/com/carefreepassserver/domain/auth/dto/TemporaryTokenDto.java
  src/main/java/org/carefreepass/com/carefreepassserver/domain/auth/dto/response/TemporaryTokenResponse.java
  src/main/java/org/carefreepass/com/carefreepassserver/domain/auth/entity/RefreshToken.java
  src/main/java/org/carefreepass/com/carefreepassserver/domain/auth/entity/TemporaryMember.java
  src/main/java/org/carefreepass/com/carefreepassserver/domain/auth/entity/TokenType.java
  src/main/java/org/carefreepass/com/carefreepassserver/domain/auth/entity/VerificationCode.java
  src/main/java/org/carefreepass/com/carefreepassserver/domain/auth/repository/RefreshTokenRepository.java
  src/main/java/org/carefreepass/com/carefreepassserver/domain/auth/repository/TemporaryMemberRepository.java
  src/main/java/org/carefreepass/com/carefreepassserver/domain/auth/repository/VerificationCodeRepository.java
  src/main/java/org/carefreepass/com/carefreepassserver/domain/auth/service/AuthService.java
  src/main/java/org/carefreepass/com/carefreepassserver/domain/auth/service/PatientAuthService.java
  src/main/java/org/carefreepass/com/carefreepassserver/domain/auth/service/TemporaryTokenService.java
  src/main/java/org/carefreepass/com/carefreepassserver/domain/auth/service/VerificationCodeService.java
  src/main/java/org/carefreepass/com/carefreepassserver/domain/member/entity/MemberRole.java
  src/main/java/org/carefreepass/com/carefreepassserver/golbal/error/ErrorCode.java
  src/main/java/org/carefreepass/com/carefreepassserver/golbal/properties/CoolsmsProperties.java
  src/main/java/org/carefreepass/com/carefreepassserver/golbal/security/JwtTokenProvider.java
  src/main/java/org/carefreepass/com/carefreepassserver/golbal/util/JwtUtil.java
  src/main/java/org/carefreepass/com/carefreepassserver/golbal/util/MemberUtil.java
  src/main/java/org/carefreepass/com/carefreepassserver/infrastructure/sms/dto/request/SmsCodeRequest.java
  src/main/java/org/carefreepass/com/carefreepassserver/infrastructure/sms/dto/request/SmsVerificationRequest.java
  src/main/java/org/carefreepass/com/carefreepassserver/infrastructure/sms/service/SmsService.java
  src/main/resources/application-coolsms.yml
  src/main/resources/application-security.yml
  src/main/resources/application.yml
Labels: Feature

#27 main push
  build.gradle
  src/main/java/org/carefreepass/com/carefreepassserver/domain/auth/controller/AuthController.java
  src/main/java/org/carefreepass/com/carefreepassserver/domain/auth/controller/docs/AuthDocs.java
  src/main/java/org/carefreepass/com/carefreepassserver/domain/auth/dto/TemporaryTokenDto.java
  src/main/java/org/carefreepass/com/carefreepassserver/domain/auth/dto/response/TemporaryTokenResponse.java
  src/main/java/org/carefreepass/com/carefreepassserver/domain/auth/entity/RefreshToken.java
  src/main/java/org/carefreepass/com/carefreepassserver/domain/auth/entity/TemporaryMember.java
  src/main/java/org/carefreepass/com/carefreepassserver/domain/auth/entity/TokenType.java
  src/main/java/org/carefreepass/com/carefreepassserver/domain/auth/entity/VerificationCode.java
  src/main/java/org/carefreepass/com/carefreepassserver/domain/auth/repository/RefreshTokenRepository.java
  src/main/java/org/carefreepass/com/carefreepassserver/domain/auth/repository/TemporaryMemberRepository.java
  src/main/java/org/carefreepass/com/carefreepassserver/domain/auth/repository/VerificationCodeRepository.java
  src/main/java/org/carefreepass/com/carefreepassserver/domain/auth/service/AuthService.java
  src/main/java/org/carefreepass/com/carefreepassserver/domain/auth/service/PatientAuthService.java
  src/main/java/org/carefreepass/com/carefreepassserver/domain/auth/service/TemporaryTokenService.java
  src/main/java/org/carefreepass/com/carefreepassserver/domain/auth/service/VerificationCodeService.java
  src/main/java/org/carefreepass/com/carefreepassserver/domain/member/entity/MemberRole.java
  src/main/java/org/carefreepass/com/carefreepassserver/golbal/error/ErrorCode.java
  src/main/java/org/carefreepass/com/carefreepassserver/golbal/properties/CoolsmsProperties.java
  src/main/java/org/carefreepass/com/carefreepassserver/golbal/security/JwtTokenProvider.java
  src/main/java/org/carefreepass/com/carefreepassserver/golbal/util/JwtUtil.java
  src/main/java/org/carefreepass/com/carefreepassserver/golbal/util/MemberUtil.java
  src/main/java/org/carefreepass/com/carefreepassserver/infrastructure/sms/dto/request/SmsCodeRequest.java
  src/main/java/org/carefreepass/com/carefreepassserver/infrastructure/sms/dto/request/SmsVerificationRequest.java
  src/main/java/org/carefreepass/com/carefreepassserver/infrastructure/sms/service/SmsService.java
  src/main/resources/application-coolsms.yml
  src/main/resources/application-security.yml
  src/main/resources/application.yml
Labels: Devops
